### ISSUE TITLE
sd_tour and slide_tour don't take kappa_max

### ISSUE THREAD

**Issue by malb** [fplll/fplll#123]
The interface of `tour()` vs. `sd_tour()` and `slide_tour()` doesn't match, in that the latter do not report the maximum `kappa` being BKZ reduced. Is that because that notion makes no sense here or is that an oversight?

**Comment by blowfish880** [comment]
this is intentional. i don't think the notion makes any sense for sd-bkz and slide reduction. for neither the clean flag plays an important role and is certainly not an indication for the basis' (non-)reducedness. in sd-bkz we're changing the basis in every tour (primal vs dual reduction), this is why auto-abort is forced to be enabled if loop or time limits are not. in slide reduction the termination condition is based on the basis' potential, since the clean-flag approach can also cause problems in combination with local preprocessing, i think.

**Comment by malb** [comment]
Okay, closing this then.
