### ISSUE TITLE
to LLL or not to LLL

### ISSUE THREAD

**Issue by malb** [fplll/fplll#137]
Over at https://github.com/fplll/fplll/pull/131/files/d6ed56afd1bffa21a24080cf0ef1be0ca30cd84a..865532ececb3abd7c856d93059e4eec98d9b3e33#r70401401 

we add an LLL call when self-dual reduction is used in order to initialise the local LLL object. The question came up whether we should call LLL unconditionally in order to put all objects always in a sane state. However `BKZ_NO_LLL` is a supported option explicitly disabling the LLL preprocessing. 

Shall we drop it? Shall we just stick with the compromise we have now?

**Comment by blowfish880** [comment]
if i remember right, damien and i discussed this a little during fplll days. i think there might be legitimate use cases for the BKZ_NO_LLL option. in particular, it might actually be numerically more stable to run bkz without running lll first, since bkz might be able to find shorter (than lll reduced) vectors during the first tour already which could make the gso computation more stable towards the end of the tour. so a bkz computation might actually finish, where an lll reduction with the same precision fails. i have to admit though, i didn't try this.

**Comment by malb** [comment]
Thanks, closing this question.
