### ISSUE TITLE
Soname numbering

### ISSUE THREAD

**Issue by SnarkBoojum** [fplll/fplll#217]
Hi,

I notice that when 5.0.3 was released, you applied the first point of the instructions on how to update the FPLLL_LT_\* variables in configure.ac ; but commit b0f613bb54266a5254f8f1e9995be43d19973e46 looks like it's modifying an interface (in fplll/enum/enumerate_base.h), so I think the second point should have applied : an interface was added.

Unless I'm mistaken, the fact that a member variable was added to a class interface means that all code trying to read/write other member variables of that class and compiled with the previous version, will now read/write to the wrong memory location with the new version, if not recompiled : the API is compatible, but the ABI is broken. A soname bump would have made old-compiled-code link to the right old-interface-library, and the new-compiled-code link to the right new-interface library.

Thanks,

Snark on #debian-science

**Comment by malb** [comment]
Hi, thanks for pointing that out. To double check I got this right: It's the line `int reset_depth;` in ` fplll/enum/enumerate_base.h` that should have triggered rule two?

**Comment by SnarkBoojum** [comment]
I think it's a new interface to the class.

**Comment by malb** [comment]
Mhh, it's a protected member. I guess a third party could inherit and use it.

**Comment by fingolfin** [comment]
Well, even if it was private: any change to the size of class instances constitues an ABI change. The reason is that when client code allocates a new instance, it has to know the size in bytes, to allocate it, and that is determined at compile time, not runtime. (If you are sceptical about that, think about placement new. Or look at existing Stackoverflow discussions, like this one: http://stackoverflow.com/questions/7699259).

BTW, also means that one should be careful about marking methods as `inline`. Strictly speaking, any change to something that  is marked `inline` may result in an ABI break, or at least in a bug fix or improvement that client code using fplll only gets to "see" after recompiling it.

All in all, for this reason I always wondered whether it really makes sense to provide heavily templatized C++ libraries like fplll in the form of a shared library in the first place

**Comment by malb** [comment]
Can you guys check if all is in order now and close this ticket if it is?

**Comment by SnarkBoojum** [comment]
I asked around and was told that changing a signature (class, function) is like removing the previous version and adding a new one, so that point 3 should apply: the triple should hence be (3, 0, 0) and not (3, 0, 1).

Sorry to blow left and then right, but the question is tricky...

**Comment by SnarkBoojum** [comment]
The KDE project, which is in C++, of course has some [documentation](https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B) on the matter.

**Comment by fingolfin** [comment]
@SnarkBoojum  Is that a typo, and you meant 4.0.0 (instead of 3.0.0)? That's at least what I'd consider to be the right value (based on what I wrote earlier, and what the interpretation you just gave nicely confirms)...

**Comment by fingolfin** [comment]
Ah, nevermind, 3.0.0 is correct -- I just looked at configure.ac and did not realize it was already updated from the old 2.x.y value.
