### ISSUE TITLE
BKZ recursive preprocessing should not run full LLL

### ISSUE THREAD

**Issue by malb** [fplll/fplll#240]
Currently, when a local block is preprocessed with smaller BKZ calls those smaller BKZ calls always run a full LLL cf. https://github.com/fplll/fplll/blob/master/fplll/bkz.cpp#L117 which shouldn't be the case.

We should either:
- inherit `BKZ.BOUNDED_LLL` from the parameters for the full BKZ or
- always use `BKZ.BOUNDED_LLL`

The second option seems like the right choice™ to me?

**Comment by blowfish880** [comment]
i don't think i agree. damien and i played around a little with the bounded_lll option during the first fplll days, and as far as i remember it seems to be a pretty risky option. in general, whenever you use this option, you might be trying to reduce blocks where the part before the block is not lll reduced, which can (and will) result in numerical problems. this is not only true globally, but also during preprocessing local blocks, i think. so this option seems only useful, when the dimension is not too large and the numbers are not too large. maybe inheriting is the right way to go here. in any case, if we decide to change this, we should make sure to check for numerical issues.

**Comment by malb** [comment]
Mhhh, when you call it recursively, the block around it is LLL reduced already because we're calling LLL on the local block first? But fair enough, some numerical experiments are needed testing this. Do you remember what kind of lattices you used for experiments?

**Comment by blowfish880** [comment]
while the basis around the block is LLL reduced, during the preprocessing vectors might be inserted that are not LLL reduced, which can result in numerical problems during the latter part of the preprocessing. i think this is what we observed. i don't remember which bases we used to see this, maybe damien remembers?

**Comment by malb** [comment]
Let `k` be the current index of the main BKZ loop and let `j >= k` be the current index for preprocessing with a smaller block size. If we were to restrict LLL between indices `k` and `k + block_size` would that be fine?

**Comment by shi-bai** [comment]
IIRC, the numerical  issues related to bounded_lll error occurs only in dual reductions. In the primal bkz tours, it seems safe to use bounded_lll (?).

**Comment by blowfish880** [comment]
to me it seems intuitive that bounded_lll would be safer on primal tours than on dual tours, but i'm not entirely convinced that it is always safe on primal tours. i'll try to do some tests before fplll days and maybe we can make a decision on that then?

**Comment by blowfish880** [comment]
i did some more testing: 
- 10 random bases for each dimension in range(60, 200,20), generated using int_rel() with bit size fixed to 1000
- run bkz with block size in range(25,55,5) using the flags: 1) default 2) bkz_bounded_lll 3) bkz_no_lll 4) bkz_bounded_lll | bkz_no_lll (so 4 independent runs with different flags)
- all invocations relied on the default recursive and pruning strategy

it seems indeed safe to run bkz with the bounded option, except when combined with no_lll. the latter case obviously results in numerical issues but they are much more severe when bounded_lll is turned on. this poses the following questions:
- is no_lll useful to keep?
- should bounded_lll be the default? what if no_lll is turned on?

for the first question, my experiments suggested that no_lll tends to be slower and give worse results, but the difference is not very big. one could argue that such an option can be useful if one already has a reduced basis and simply wants to obtain a stronger reduced basis, but in such a case, lll will probably run very fast, so the gain is limited. another possibility that i have argued for in the past is that there could be strange bases, where running bkz directly could be numerically more stable (note that the vectors bkz finds in the first steps could be much shorter than the ones that lll returns, which tends to make the gram schmidt computation more stable), but i didn't encounter any such bases and it seems one would need very contrived examples. in summary, one could consider removing this option.

about the second question, in my experiments there was not really a clear winner between the default flags and bounded_lll. if one was slower than the other, it usually also returned higher quality bases (measured by the length of the first vector). there were only very rare cases where one performed better in both running time and output quality, and they went either way. i also repeated the experiment, where the recursive calls inherited the bounded_lll behavior from the top level parameter. again, i did not see too much difference (it seemed to improve the bounded_lll version slightly). 

in any case, in my opinion, the most intuitive would be if the flag was simply inherited (same goes for the bkz_gh_bnd flag i think, but it didn't touch that for now) since this is what i would expect as user. and since it does not seem to make a big difference performance wise, we might as well. thoughts?
