### ISSUE TITLE
Remove the sieve?

### ISSUE THREAD

**Issue by malb** [fplll/fplll#369]
With G6K being a thing, shall we remove the Gauss sieve again?

**Comment by lgremy** [comment]
IMO, I think we need to answer (I tried to) to several questions before doing this.

1. Is the code active (i.e., commits are not just for maintenance)? It seems not, according to the log inside the sieve directory.
2. Is the code maintained? Yes
* Is it tedious to maintain the code? I do not know, but I suppose this issue is also a consequence of PR #368, in addition to the new direction sieve algorithms take with G6K
3. Is the code tested? A little
4. Is the code used as a dependency of pieces of software? I have no idea

If I correctly understood (I am not a specialist), with [the G6K implementation](https://github.com/fplll/g6k), G6K outperforms the known results about practical sieving, and then the sieve implementation inside fplll introduced with [BLS16]. However, since this code is linked to a research article, if we remove the Gauss sieve implementation from fplll, I suggest that we will freeze the code in a specific and well-identified branch, in order for a further use to be an option.

**Comment by shi-bai** [comment]
Hi Laurent, Martin,

Thanks for bringing this up.
On Fri, May 17, 2019 at 3:10 AM Laurent Grémy <notifications@github.com>
wrote:

> IMO, I think we need to answer (I tried to) to several questions before
> doing this.
>
>    1. Is the code active (i.e., commits are not just for maintenance)? It
>    seems not, according to the log inside the sieve directory.
>    2. Is the code maintained? Yes
>
>
>    - Is it tedious to maintain the code? I do not know, but I suppose
>    this issue is also a consequence of PR #368
>    <https://github.com/fplll/fplll/pull/368>, in addition to the new
>    direction sieve algorithms take with G6K
>
>
>    1. Is the code tested? A little
>    2. Is the code used as a dependency of pieces of software? I have no
>    idea
>
> If I correctly understood (I am not a specialist), with the G6K
> implementation <https://github.com/fplll/g6k>, G6K outperforms the known
> results about practical sieving, and then the sieve implementation inside
> fplll introduced with [BLS16]. However, since this code is linked to a
> research article, if we remove the Gauss sieve implementation from fplll, I
> suggest that we will freeze the code in a specific and well-identified
> branch, in order for a further use to be an option.
>
This looks good to me. I think we could leave the code in a specific branch
(just in case anyone wanted to read the code with the paper).

Cheers,
Shi

**Comment by malb** [comment]
Let's reopen this discussion. I still vote for moving it to a separate branch.

**Comment by lducas** [comment]
I agree with Martin

**Comment by joerowell** [comment]
Just to throw another option into the ring - it may behoove us to implement an external sieving interface (similarly to enumerate_ext.h) in the future (in a major release of fplll, not 5.3.0).  

I say this because:
a) Sieving is a very active area, & I suspect there'll be a few new implementations in the distant future. It'd be quite nice to be able to plug some of these directly into fplll, or adapt them if they're not natively suited for this. It'd also potentially make implementing new sieves easier - for a research library, I think this is important.
b) If there's not appetite for a "breaking change" - i.e keeping backwards compatibility - then we can implement an approach similar to multi-threaded enumeration, where there's a fallback to fplll's internal sieve if certain options aren't supported. 
c) It may enable us to build a new hierarchy of evaluators, where we abstract away which SVP method is being called in some algorithm (say, the implementation of BKZ). This could give a large deal of potential options depending on real-world constraints (i.e a low memory environment, or in situations where the blocksize is < 70 in a progressive BKZ implementation).

However I appreciate that this may be infeasible - and regardless, I don't see any reason why moving it to a separate, well-identified branch/tag isn't a good solution.

**Comment by malb** [comment]
Hi there, my understanding of the current code base is that it wouldn't easily allow us to do what you'd like to do. The sieve as it stands is pretty much separate from the rest of the code base, e.g. doesn't use GSO objects, which means it probably wouldn't be a good platform to develop an API from? I'm not suggesting: let's not have sieving, but I'm asking if this sieve implementation might be better moved to a branch.

**Comment by joerowell** [comment]
I know this has been quiet for a while, but a good reason for moving this to a separate branch would be that every time G6K is compiled right now, we also compile the sieve from fplll. This is clearly nonsensical, as G6K supersedes this sieve. This is a consequence of #393, so it could be fixed that way too (i.e by reinstating optional compilation), but I figured it'd be a good chance to revisit this.

**Comment by lducas** [comment]
I guess the right question is:

Is there anyone actually (still) using this code ? I suspect most of the potential users are contributors to FPLLL. How about we ask this question to the fplll list, and acts accordingly.

**Comment by shi-bai** [comment]
Sounds good to me: freeze the code in a separate branch.
