### ISSUE TITLE
bkz_reduction and BKZ_AUTO_ABORT

### ISSUE THREAD

**Issue by johughes99** [fplll/fplll#423]
I have a query about how auto abort and max_time works.

my code contains the following snippet:

`vector<Strategy> strategies;
BKZParam param(blockSize, strategies);
param.flags = BKZ_DEFAULT|BKZ_AUTO_ABORT|BKZ_MAX_TIME;
param.max_time = 120;

status = bkz_reduction(lattice, NULL, param ,FT_DEFAULT, 0);`

In some timing tests I have performed suggests that the BKZ timeout only kicks in much later than the max_time parameter. So for instance on BKZ-53 reduction on a 90 dimension lattice the timeout message appeared after 11,547 seconds - not after the 120 seconds I had expected.

Whilst on a similar subject - when firing in the same data set into fpylll (again using a 90 dimension lattice) - the BKZ-53 analysis would not time out and took tens of seconds - rather than the 3 hours or so fplll took.

The fpyll code being:

`BKZ.reduction(lattice, BKZ.Param(block_size=block_size, strategies=BKZ.DEFAULT_STRATEGY, auto_abort=True)`

So my additional question is whether the fplll and fpylll calls provided above are functionality equivalent.

**Comment by shi-bai** [comment]
Hi Johughes99,

Did you use the ./fplll command line interface or call the function via the fplll lib in your code?

In case you used ./fplll, there seems to be a bug -- fixed in the current pull request: the bkzmaxtime was not parsed into the function bkz().

In the second case (and independent from the bug), the "bkzmaxtime" option only triggers after the competition of a whole BKZ tour. See documentation: 

-bkzmaxtime time : stops after time seconds (up to completion of the current loop iteration).

Thus, if the whole BKZ tour takes a long time, say 11,547 seconds, the check that 11547 > 120 condition is only triggered at this point. 

Back to the reason that it takes much longer time for your first trial, it seems that "no pruning" is used in your code. Thus the whole BKZ tour takes a long time.

For the trial using fpylll, it runs faster since you used pruning with the option "strategies=BKZ.DEFAULT_STRATEGY". 

Could you try to run them again with the same pruning strategy?

**Comment by johughes99** [comment]
Hi Si,

I'm using the function call directly in my code.

Are you saying that for something like BKZ-53 with a dim of 90 a whole tour could take 11,536 seconds - using the default strategy?

in the case of fpylll and the bkz_reduction() call what is the strategy it uses?

I will try different strategies later today and see what happens

**Comment by shi-bai** [comment]
> Are you saying that for something like BKZ-53 with a dim of 90 a whole tour could take 11,536 seconds - using the default strategy?

I mean "no pruned enumeration" has been used in your fplll code -- thus it's "full" enumeration which is slow. For the wording, I didn't refer to this as "default strategy".

While in your fpylll code, the default strategy (which uses the "pruned enumeration" provided in fplll). This loads the pre-computed strategy in the default.json file. For the wording, this is named the "default strategy".

To get equivalent code in fplll, one can use similar code in test_bkz_param_pruning() in test_bkz.cpp.

**Comment by johughes99** [comment]
Si

I loaded the json file into the strategies vector and now the timings for fplll do now appear to be very similar to those with fpylll

BTW - if you supply the wrong name for the json file (ie its missing) - as I did accidentally - you get an exception.

**Comment by shi-bai** [comment]
> BTW - if you supply the wrong name for the json file (ie its missing) - as I did accidentally - you get an exception.

Yes, it loads the pre-built file "default.json" under the ./strategies folder.
