### ISSUE TITLE
Deleting ZZ_mat<mpz_t> lattice and associated elements

### ISSUE THREAD

**Issue by johughes99** [fplll/fplll#428]
In my use case I will be creating a lattice, using it, and then creating a new lattice  - looping around many times.

I create the lattice by calling:

`ZZ_mat<mpz_t> lattice = ZZ_mat<mpz_t>(dim+2, dim+2);`

To make sure I dont have any memory leakage I wish to delete/deconstruct the current lattice before creating a new lattice.

Whist I see there is a clear() method I'm not sure if this does what I want.

How do i go about deleting all the lattice elements and then finally delete the lattice itself.

I had expected a `ZZ_mat<mpz_t> deconstructor that would do this - but cant see one.

**Comment by joerowell** [comment]
When you declare a variable in C++ without the new operator, you don't need to call delete. 

This is because the C++ runtime system will clear this up for you, and so there's no need to manually call delete. You can think of this as similar to using ```int x``` or ```double y```; here, C++ defaults to treating this type as if it were a stack variable. So, the C++ runtime system frees any memory allocated for you - there's no need to do anything on your part.

To illustrate this, here's an example segment:
``` 
 #include<fplll.h>
 #include<iostream>
 
 void test() {
     for(unsigned i = 0; i < 10; i++) {
         ZZ_mat<mpz_t> mat = ZZ_mat<mpz_t>(2,2);
         mat(1,0) = rand();
         mat(0,1) = rand();
         std::cout << mat << std::endl << std::endl;
     }
 }
 
 
 int main() {
     srand(time(NULL));
     test();
     return 0;
 }
```

Compiled with ```g++ -g -lfplll -lmpfr -lgmp -lpthread -o test test.cpp ``` and ran with ``` valgrind ./test```, you should get the following output (or similar):

```
==3975== HEAP SUMMARY:
==3975==     in use at exit: 0 bytes in 0 blocks
==3975==   total heap usage: 4,226 allocs, 4,226 frees, 143,738 bytes allocated
==3975== 
==3975== All heap blocks were freed -- no leaks are possible
```

So, as you can see, there's nothing you need to do here - the language does it for you.
