### ISSUE TITLE
hkz fail (Failure: infinite loop in babai) with mpfr

### ISSUE THREAD

**Issue by shi-bai** [fplll/fplll#52]
given the attached input, using

fplll  -a hkz -f mpfr -p NNN raw_matrix_h.txt

fails with "Failure: infinite loop in babai"

with NNN = 1000 to 10000

However, using bkz with high blocksize works. It might be a small bug. (logged here and to be identified)

[raw_matrix_h.txt](https://github.com/dstehle/fplll/files/98114/raw_matrix_h.txt)

**Comment by dstehle** [comment]
Hi Shi,

Did you try running just "fplll" on it  (without hkz without mpfr)
and "fplll -f mpfr - p 1000" (without hkz)?
With the verbose mode?

Regards
Damien

**Comment by shi-bai** [comment]
Hi Damien,

The wrapper method does not support the specification of mpfr:

fplll  -f mpfr -p 1000 raw_matrix_h.txt
fplll: The floating point type cannot be specified with the wrapper method
Aborted

I tried to debug it a bit right now. The previous fplll -a hkz stopped at
the enumeration procedure. The output matrix (just before the error) is LLL
reduced. It reports the error when it starts to do the actual enumeration:

# Tour number [0]
 [enum] svp kappa 0, kappa+b 128 lllstart 0
 !!!!!!!!!!! failed here
 start 0
 blockSize 128

This and the other problem in the bug list seem relevant to the precision
in enumeration.

Best,
Shi

**Comment by dstehle** [comment]
Hi Shi,

On 21 January 2016 at 23:49, shi-bai <notifications@github.com> wrote:

> Hi Damien,
>
> The wrapper method does not support the specification of mpfr:
>

You mean 'fplll'. Because the intent of  "fplll -f mpfr" is to not use the
wrapper!



> fplll -f mpfr -p 1000 raw_matrix_h.txt
> fplll: The floating point type cannot be specified with the wrapper method
> Aborted
>

That should be possible. Isn't it odd? This seems like an extra bug to me.


I tried to debug it a bit right now. The previous fplll -a hkz stopped at
> the enumeration procedure. The output matrix (just before the error) is LLL
> reduced. It reports the error when it starts to do the actual enumeration:
>
> # Tour number [0]
> [enum] svp kappa 0, kappa+b 128 lllstart 0
> !!!!!!!!!!! failed here
> start 0
> blockSize 128
>
> This and the other problem in the bug list seem relevant to the precision
> in enumeration.
>
>
It does LLL fine, and then crashes when it starts enumeration, before
actually
doing anything in the enumeration?

Very odd too...

Damien



>
>

**Comment by blowfish880** [comment]
i just looked into this a little bit. the issue seems to be that hkz ignores any input regarding the floating point type and precision and only runs in FT_DEFAULT=FT_DOUBLE. the options are passed to the hkz function in the main.cpp, but the hkzReduction function in fplll.h/cpp doesn't allow to pass it a floating point type, so it is ignored from that point on.

not surprisingly, if you run bkz with default FT type and blocksize 128 on the given input, it also fails with the same error.

**Comment by shi-bai** [comment]
I remembered we were discussing about some potential bugs with the precision here. I just tried  

./fplll -a lll   raw_matrix_h.txt  -v -v

double precision 
Discovering vector 83/128 cputime=684
End of LLL: failure: infinite loop in babai

Thus with double, it fails very quickly at = 83. This is not the case in general, I guess.
