### ISSUE TITLE
BKZ transformation matrix is incorrect when nrows > ncols

### ISSUE THREAD

**Issue by TheBlupper** [fplll/fplll#525]
This is an issue in fplll and can be replicated in the CLI, but here is a proof of context in fpylll for simplicity's sake
```py
import copy
from fpylll import FPLLL, IntegerMatrix, BKZ, LLL
FPLLL.set_random_seed(1337)
nrows, ncols = 20, 19
R = IntegerMatrix.random(nrows, 'uniform', bits=10)
A = IntegerMatrix(nrows, ncols)
for i in range(R.nrows):
    for j in range(ncols):
        A[i, j] = R[i, j]
B = copy.copy(A)
U = IntegerMatrix(10, 10)
BKZ.reduction(A, BKZ.Param(3), U=U)
print(A == U * B)
```
U contains some numbers with very strange bit patterns.

**Comment by malb** [comment]
This only happens if A is not full rank, right? Given that we're exposing a low-level API here, should we simply document this and accept it?

**Comment by malb** [comment]
I asked on the mailing list if people have opinions. I don't have a strong one, I just expect there's a lot of this sort of stuff lurking in the code base.

**Comment by joerowell** [comment]
The issue is here:

https://github.com/fplll/fplll/blob/143feabe12cd8f529e708ef4da735df474e57087/fplll/bkz.cpp#L859-L862

Because that function assumes that `U` is full rank. I suspect a quick fix is just to resize it appropriately, fill with zeros, and then fill the "full rank part" with the identity?
